"""
Governance Assistant — LLM-powered Q&A over audit report data.
Uses Groq's free API with llama-3.3-70b-versatile.
"""
import json
from pathlib import Path
from groq import Groq


def ask_governance_assistant(question: str, audit_bundle: dict) -> str:
    """
    Send a governance question to the LLM with full audit context.

    Args:
        question:     Plain English question from the user
        audit_bundle: Audit bundle dict from build_audit_bundle()

    Returns:
        LLM response as a string
    """
    client = Groq(api_key="my api key")  # ← Replace with your key

    # Extract all relevant sections from audit bundle
    model_metrics  = audit_bundle['artifacts'].get('model_metrics', {}) or {}
    fairness       = audit_bundle['artifacts'].get('fairness', {}) or {}
    explainability = audit_bundle['artifacts'].get('explainability', {}) or {}
    dataset        = audit_bundle['artifacts'].get('dataset_profile', {}) or {}
    trajectory     = audit_bundle['artifacts'].get('trajectory', {}) or {}

    # Build concise context — trim SHAP to top 5 to save tokens
    shap_values = explainability.get('mean_abs_shap', {})
    top_shap = dict(sorted(shap_values.items(), key=lambda x: x[1], reverse=True)[:5])

    # Trim trajectory bucket performance
    bucket_perf = trajectory.get('bucket_performance', [])

    context = f"""
You are an expert Model Risk Management and AI Governance assistant working in financial services.
You have access to the following audit report generated by an ML Governance System.
Answer the user's question based strictly on this data. Be concise, accurate, and use plain English
suitable for a risk officer, data scientist, or regulator. If the data does not contain enough
information to answer the question, say so clearly.

=== DATASET PROFILE ===
Rows: {dataset.get('rows', 'N/A')}
Columns: {dataset.get('columns', 'N/A')}
Target: {dataset.get('target', 'N/A')}
Class Distribution: {json.dumps(dataset.get('target_counts', {}), indent=2)}
Missing Values: {json.dumps(dataset.get('missingness_percent_top', {}), indent=2)}

=== MODEL PERFORMANCE ===
Accuracy: {model_metrics.get('accuracy', 'N/A')}
Tuned Accuracy: {model_metrics.get('tuned_accuracy', 'N/A')}
ROC AUC: {model_metrics.get('roc_auc', 'N/A')}
Optimal Threshold: {model_metrics.get('optimal_threshold', 'N/A')}
Weighted Avg F1: {model_metrics.get('classification_report', {}).get('weighted avg', {}).get('f1-score', 'N/A')}

=== FAIRNESS ASSESSMENT ===
Demographic Parity Difference: {fairness.get('demographic_parity_difference', 'N/A')}
Equalized Odds Difference: {fairness.get('equalized_odds_difference', 'N/A')}
Regulatory Threshold: 0.20 (values above this indicate high bias)

=== TOP 5 SHAP FEATURES ===
{json.dumps(top_shap, indent=2)}

=== GROUP PERFORMANCE (by sensitive attribute) ===
{json.dumps(bucket_perf, indent=2)}
"""

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",  # ✅ Best free model on Groq
        messages=[
            {"role": "system", "content": context},
            {"role": "user",   "content": question}
        ],
        max_tokens=512,
        temperature=0.3,  # Lower = more factual, less creative
    )

    return response.choices[0].message.content


def load_audit_bundle(reports_dir: str = "reports") -> dict:
    """
    Load the latest audit bundle from the reports directory.
    Useful for standalone testing outside the dashboard.
    """
    reports_path = Path(reports_dir)
    audit_json = reports_path / "audit_report.json"

    if not audit_json.exists():
        return {"artifacts": {}}

    with open(audit_json, "r", encoding="utf-8") as f:
        return json.load(f)


# ---------------------------------------------------------------------------
# Quick test — run directly to verify your API key works
# ---------------------------------------------------------------------------
if __name__ == "__main__":
    print("Loading audit bundle...")
    bundle = load_audit_bundle("reports")

    test_questions = [
        "Is this model safe to deploy based on the fairness metrics?",
        "What are the top risk factors driving predictions?",
        "Which demographic group has the lowest prediction accuracy?",
        "Summarise this audit report for a non-technical stakeholder.",
    ]

    for q in test_questions:
        print(f"\nQ: {q}")
        print(f"A: {ask_governance_assistant(q, bundle)}")
        print("-" * 60)